import 'dart:typed_data';
import 'package:flutter/foundation.dart';
import 'package:archive/archive.dart';
import '../models/image_reducer_state.dart';

class ExportUtils {
  static Future<Uint8List> createZipFromImages(
    List<ProcessedImage> images, {
    bool includeOriginals = false,
  }) async {
    final result = await compute(_createZipIsolate, {
      'images': images,
      'includeOriginals': includeOriginals,
    });
    return result['data'] as Uint8List;
  }

  static Map<String, dynamic> _createZipIsolate(Map<String, dynamic> params) {
    final images = params['images'] as List<ProcessedImage>;
    final includeOriginals = params['includeOriginals'] as bool;

    final archive = Archive();

    for (final image in images) {
      try {
        // Add processed image if available
        if (image.processedData != null) {
          final processedFileName = _getProcessedFileName(image);
          final processedFile = ArchiveFile(
            processedFileName,
            image.processedData!.length,
            image.processedData,
          );
          archive.addFile(processedFile);
        }

        // Add original if requested
        if (includeOriginals) {
          final originalFileName = 'originals/${image.fileName}';
          final originalFile = ArchiveFile(
            originalFileName,
            image.originalData.length,
            image.originalData,
          );
          archive.addFile(originalFile);
        }
      } catch (e) {
        // Log error but continue with other files
        continue;
      }
    }

    // Add summary file
    final summary = _generateSummaryText(images);
    final summaryFile = ArchiveFile(
      'processing_summary.txt',
      summary.length,
      Uint8List.fromList(summary.codeUnits),
    );
    archive.addFile(summaryFile);

    final zipData = ZipEncoder().encode(archive);
    return {
      'data': Uint8List.fromList(zipData!),
      'fileCount': archive.files.length - 1, // Excluding summary
    };
  }

  static String _getProcessedFileName(ProcessedImage image) {
    final originalName = image.fileName;
    final lastDotIndex = originalName.lastIndexOf('.');

    if (lastDotIndex == -1) {
      return '${originalName}_reduced';
    }

    final nameWithoutExtension = originalName.substring(0, lastDotIndex);
    final extension = image.detectedFormat?.extension ??
                     originalName.substring(lastDotIndex + 1);

    return '${nameWithoutExtension}_reduced.$extension';
  }

  static String _generateSummaryText(List<ProcessedImage> images) {
    final buffer = StringBuffer();

    buffer.writeln('BharatTesting Utilities - Image Processing Summary');
    buffer.writeln('=' * 50);
    buffer.writeln();

    final processedImages = images.where((img) => img.isProcessed).toList();
    final totalOriginalSize = images.fold<int>(
      0,
      (sum, img) => sum + img.originalFileSize,
    );
    final totalProcessedSize = processedImages.fold<int>(
      0,
      (sum, img) => sum + (img.processedFileSize ?? 0),
    );

    buffer.writeln('BATCH STATISTICS');
    buffer.writeln('-' * 20);
    buffer.writeln('Total Images: ${images.length}');
    buffer.writeln('Successfully Processed: ${processedImages.length}');
    buffer.writeln('Failed: ${images.length - processedImages.length}');
    buffer.writeln();

    if (totalOriginalSize > 0) {
      final reductionBytes = totalOriginalSize - totalProcessedSize;
      final reductionPercent = (reductionBytes / totalOriginalSize) * 100;

      buffer.writeln('SIZE REDUCTION');
      buffer.writeln('-' * 20);
      buffer.writeln('Original Total: ${_formatFileSize(totalOriginalSize)}');
      buffer.writeln('Processed Total: ${_formatFileSize(totalProcessedSize)}');
      buffer.writeln('Space Saved: ${_formatFileSize(reductionBytes)}');
      buffer.writeln('Reduction: ${reductionPercent.toStringAsFixed(1)}%');
      buffer.writeln();
    }

    buffer.writeln('INDIVIDUAL FILES');
    buffer.writeln('-' * 20);

    for (int i = 0; i < images.length; i++) {
      final image = images[i];
      buffer.writeln('${i + 1}. ${image.fileName}');

      if (image.isProcessed) {
        buffer.writeln('   Original: ${image.originalFileSizeText}');
        buffer.writeln('   Processed: ${image.fileSizeText}');
        buffer.writeln('   Reduction: ${image.reductionPercentageText}');
        if (image.detectedFormat != null) {
          buffer.writeln('   Format: ${image.detectedFormat!.displayName}');
        }
      } else {
        buffer.writeln('   Status: ${image.status.displayName}');
        if (image.error.isNotEmpty) {
          buffer.writeln('   Error: ${image.error}');
        }
      }
      buffer.writeln();
    }

    buffer.writeln('Generated by BharatTesting Utilities');
    buffer.writeln('https://bharattesting.com');

    return buffer.toString();
  }

  static String _formatFileSize(int bytes) {
    if (bytes < 1024) {
      return '$bytes B';
    } else if (bytes < 1024 * 1024) {
      return '${(bytes / 1024).toStringAsFixed(1)} KB';
    } else if (bytes < 1024 * 1024 * 1024) {
      return '${(bytes / (1024 * 1024)).toStringAsFixed(1)} MB';
    } else {
      return '${(bytes / (1024 * 1024 * 1024)).toStringAsFixed(1)} GB';
    }
  }

  static Future<void> downloadFile({
    required Uint8List data,
    required String fileName,
    required String mimeType,
  }) async {
    // Platform-specific download implementation
    if (kIsWeb) {
      await _downloadWebFile(data, fileName, mimeType);
    } else {
      await _downloadMobileFile(data, fileName);
    }
  }

  static Future<void> _downloadWebFile(
    Uint8List data,
    String fileName,
    String mimeType,
  ) async {
    // Web download implementation using blob URLs
    // This would be implemented using dart:html in real implementation
    // For now, just a placeholder
    throw UnsupportedError('Web download not implemented in this demo');
  }

  static Future<void> _downloadMobileFile(
    Uint8List data,
    String fileName,
  ) async {
    // Mobile download implementation using path_provider + share_plus
    // This would save to app documents directory and share via OS
    throw UnsupportedError('Mobile download not implemented in this demo');
  }

  static String generateFileName({
    required String baseName,
    bool isBatch = false,
    String? format,
  }) {
    final now = DateTime.now();
    final timestamp = '${now.year}${now.month.toString().padLeft(2, '0')}'
        '${now.day.toString().padLeft(2, '0')}_'
        '${now.hour.toString().padLeft(2, '0')}'
        '${now.minute.toString().padLeft(2, '0')}'
        '${now.second.toString().padLeft(2, '0')}';

    if (isBatch) {
      return 'bharattesting_images_$timestamp.zip';
    } else {
      final extension = format ?? 'jpg';
      return '${baseName}_$timestamp.$extension';
    }
  }
}

extension ProcessingStatusDisplay on ProcessingStatus {
  String get displayName {
    switch (this) {
      case ProcessingStatus.pending:
        return 'Pending';
      case ProcessingStatus.processing:
        return 'Processing';
      case ProcessingStatus.completed:
        return 'Completed';
      case ProcessingStatus.error:
        return 'Error';
    }
  }
}